---
version: "3.7"

networks:
  traefik:
    external: true 

services: 
  "app":
    container_name: "dev-albums-api"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.albums.rule=Host(`dev.api.albums.$DOMAINNAME`)"
      - "traefik.http.services.albums.loadbalancer.server.port=30000" 
