---
version: "3.7"

services: 
  app:
    image: "node:current-alpine"
    working_dir: /home/node/app
    volumes:
      - ./node_modules:/home/node/app/node_modules:delegated
      - .:/home/node/app:consistent
    ports:
      - 30000:30000
    environment:
      - JWT_DOMAIN=$JWT_DOMAIN
      - JWT_AUDIENCE=$JWT_AUDIENCE
      - PORT=$PORT
    entrypoint: "npm"

volumes:
  cache:
